name: Scrape latest Covid data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    # Use Web Request Action to fetch data
    - name: Fetch latest data using Web Request Action
      id: fetchdata
      uses: satak/webrequest-action@master
      with:
        url: https://api.hygiene-monitor.de/openData/getCovidOpenDataByDateRange
        method: POST
        payload: '{"extraction_date_start": "2023-09-21","extraction_date_end": "2023-10-22"}'
        
    # Save the response content to a file
    - name: Echo response
      run: echo '${{ steps.fetchdata.outputs.content }}' 
    - name: Save response to incidents.json
      run: echo '${{ steps.fetchdata.outputs.content }}' > covidStats.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/timd/covidstats.git HEAD:master
