name: Scrape latest Covid data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    # Use Web Request Action to fetch data
    - name: Get current date
      id: current_date
      run: echo "{current_date}={$(date +'%Y-%m-%d')}" >> $GITHUB_OUTPUT

    - name: Get date from 5 days ago
      id: five_days_ago
      run: echo "{fiveDaysAgo}={$(date -d '5 days ago' +'%Y-%m-%d')}" >> $GITHUB_OUTPUT

    - name: Use date in a shell command
      run: echo "Today's date is ${{ steps.current_date.outputs.current_date }}"

    - name: Use date in a shell command
      run: echo "5 days ago's date is ${{ steps.five_days_ago.outputs.fiveDaysAgo }}"
      
    - name: Fetch latest data using Web Request Action
      id: fetchdata
      uses: satak/webrequest-action@master
      with:
        url: https://api.hygiene-monitor.de/openData/getCovidOpenDataByDateRange
        method: POST
        payload: '{"extraction_date_start": "2023-09-21","extraction_date_end": "2023-10-22"}'
        
    # Save the response content to a file
    - name: Echo response
      run: echo '${{ steps.fetchdata.outputs.output }}' 
    - name: Save response to incidents.json
      run: echo '${{ steps.fetchdata.outputs.output }}' > covidStats.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/timd/covidstats.git HEAD:main
