name: Scrape latest Covid data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    # Set params for request

    - name: Set current date
      id: set_current_date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

    - name: Print current date
      env:
        CURRENT_DATE: ${{ steps.set_current_date.outputs.CURRENT_DATE }}
      run: echo "Today's date is ${{ steps.set_current_date.outputs.CURRENT_DATE }}"
    
    - name: Set date from 3 days ago
      id: three_days_ago
      run: echo "THREE_DAYS_AGO=$(date -d '3 days ago' +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

    - name: Print three days ago
      env:
        THREE_DAYS_AGO: ${{ steps.five_days_ago.outputs.THREE_DAYS_AGO }}
      run: echo "3 days ago's date is $THREE_DAYS_AGO"

    # Use Web Request Action to fetch data
      
    - name: Fetch latest data using Web Request Action
      id: fetchdata
      uses: satak/webrequest-action@master
      with:
        url: https://api.hygiene-monitor.de/openData/getCovidOpenDataByDateRange
        method: POST
        payload:  '{"extraction_date_start": "${{ steps.three_days_ago.outputs.THREE_DAYS_AGO }}","extraction_date_end": "${{ steps.set_current_date.outputs.CURRENT_DATE }}"}'
        
    # Save the response content to a file
    - name: Echo response
      run: echo '${{ steps.fetchdata.outputs.output }}' 
    - name: Save response to incidents.json
      run: echo '${{ steps.fetchdata.outputs.output }}' > covidStats.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/timd/covidstats.git HEAD:main
